
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%=ENV['LUNCHPRO_DATABASE_HOST']%>
  database: <%=ENV['LUNCHPRO_DATABASE_NAME']%>
  username: <%=ENV['LUNCHPRO_DATABASE_USERNAME']%>
  password: <%= ENV['LUNCHPRO_DATABASE_PASSWORD'] %>
  pool: 25

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
